
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtpractice
    username: postgres
    password: amin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      properties:
        hibernate:
          format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 28472B4B6250655368566D597133743677397A24432646294A404D635166546A
      expiration: 86400000
      refresh-token:
        expiration: 604800000
